export const API_BASE_URL = "https://placement-cell-management-backend.onrender.com";
export const API_ENDPOINT = API_BASE_URL + "/api/v1/"

export const courses = [
    "B.Tech(CSE)",
    "B.Tech(ECE)",
    "B.Tech(EE)",
    "B.Tech(ME)",
    "M.Tech(CSE)",
    "MBA(Finance)",
    "MBA(Marketing)",
    "MBA(HR)",
    "BBA",
    "BBA",
    "BCA",
    "MCA",
    "MCA",
    "B.Sc(Physics)",
    "B.Sc(Chemistry)",
    "B.Sc(Mathematics)",
    "M.Sc(Physics)",
    "M.Sc(Chemistry)",
    "M.Sc(Mathematics)",
    "B.Com(General)",
    "B.Com(Accounting)",
    "B.Com(Finance)",
    "M.Com(General)",
    "M.Com(Accounting)",
    "M.Com(Finance)",
    "BA(English)",
    "BA(History)",
    "BA(Political Science)",
    "MA(English)",
    "MA(History)",
    "MA(Political Science)"
];
